### ISSUE TITLE
Custom release title

### ISSUE THREAD

**Issue by BelKed** [fregante/release-with-changelog#27]
Hey fregante,

I would like to request to add **custom title** option. Default it will be just tag name (`{tag}`). You could change it like follows:

```yaml
...
- name: Create release with custom title
  uses: fregante/release-with-changelog@v3
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    title: Version {tag}
```

That will produce release with title `Version 3.1.0` (when is tag `3.1.0`).

PS: Thanks for making very useful Github Action. It helps me a lot 😄

**Comment by BelKed** [comment]
It's seems to be simple. After merging my other pull request I will look at it.
More info can be found here: https://octokit.github.io/rest.js/v18/#repos-create-release...

**Comment by fregante** [comment]
I think we should just become a wrapper around [actions/create-release](https://github.com/actions/create-release) so we immediately support everything it supports by re-exporting this file: https://github.com/actions/create-release/blob/main/action.yml

Or, really, the only things that this action does over `actions/create-release` I think are:

- automatically picking the latest tag if not supplied
- generating the changelog

I can look into adding the first bullet to `actions/create-release` itself and the second part can be handled via #35 

```yml
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

would become

```yml
      - run: npx release-with-changelog@3 > changelog.md
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: changelog.md
```

And we'd automatically gain #31 and this feature, among others.

Maybe I can convince them to also automatically pickup some special field or ENV and it'd become even shorter
