### ISSUE TITLE
Reverse sort option

### ISSUE THREAD

**Issue by BelKed** [fregante/release-with-changelog#28]
Hey fregante,

I would like to request to add **sort by date option**. In this option you could set if you want to sort commits ascending (from older to newer) or descending (from newer to older – like now and it will be default). You could change it like follows:

```yaml
...
- name: Create release with commits sorted ascending 
  uses: fregante/release-with-changelog@v3
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    sort: ascending
```

That will produce release with body, where will be commits sorted ascending (from older to newer).
I think, it's better to have commits sorted ascending – you could look on "development process" and it's better for understanding what happened.
