### ISSUE TITLE
Author placeholder/replacement

### ISSUE THREAD

**Issue by BelKed** [fregante/release-with-changelog#29]
Hey fregante,

I would like to request to add **author placeholder/replacement of commit**. You could add this placeholder  – `{author}` to `commit-template` where it will "print" author name. You could add it like follows:

```yaml
...
- name: Create release with authors
  uses: fregante/release-with-changelog@v3
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    commit-template: '- {hash} {title} {author}'
```

And it will produce release with text `- 6e89f5c Update user in examples @fregante`:
- 6e89f5c Update user in examples @fregante

It's better to see it written in changelog or in mail notification, not just after hovering or opening commit.
