### ISSUE TITLE
Date placeholder/replacement

### ISSUE THREAD

**Issue by BelKed** [fregante/release-with-changelog#30]
Hey fregante,

I would like to request to add **date placeholder/replacement of commit**. You could add this placeholder – `{date}` to `commit-template` where it will "print" date of commit and adds link to commit on it. You could add it like follows:

```yaml
...
- name: Create release with date
  uses: fregante/release-with-changelog@v3
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    commit-template: '- {date} {title}'
```

And it will produce release with text `- [4.2.2021](https://github.com/fregante/release-with-changelog/commit/6e89f5c9d6622f54ca284c06aa89fa7391cd86f7) Update user in examples`:

- [4.2.2021](https://github.com/fregante/release-with-changelog/commit/6e89f5c9d6622f54ca284c06aa89fa7391cd86f7) Update user in examples

It's better to have date (pointing to commit) instead of commit hash in changelog or in mail notification.
