### ISSUE TITLE
commit-template {date}  variable failing

### ISSUE THREAD

**Issue by fredbradley** [fregante/release-with-changelog#37]
I can't get the `{date}` to show up in the commit-template. 

Code in my action: 
```
     - uses: fregante/release-with-changelog@v3
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-template: '- {date} {title} ← {hash}'
          template: |
              ### Changelog
              {commits}

              Compare: {range}

              ❤
```

Output
![image](https://user-images.githubusercontent.com/1639226/109076073-ecfafe00-76f1-11eb-92b5-a53183c42273.png)
