### ISSUE TITLE
Add way to exclude commits via regex

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#4]
`npm version` creates a commit that shouldn't appear:

<img width="478" alt="" src="https://user-images.githubusercontent.com/1402241/92772440-a1e36d80-f393-11ea-9d21-81369c9a3539.png">

vercel/release automatically excludes it already:

https://github.com/fregante/github-url-detection/releases

With a regex I'd be able to also exclude `Meta: ` commits from Refined GitHub:

```yml
      - uses: notlmn/release-with-changelog@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '^Meta:|^Docs:'
```
