### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [fregante/release-with-changelog#54]
Here is my release.yml file

```
name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: fregante/release-with-changelog@v3.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '^build:|^chore:|^ci:|^docs:'
          commit-template: '- {title} ← {hash}'
          template: |
              ### Release Notes

              {commits}

              {range}

              🚀
        id: Changelog
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
```

However when my workflow is being executed on GitHub, I get the following error at the Changelog step:

```
Run fregante/release-with-changelog@v3.5.1
file:///home/runner/work/_actions/fregante/release-with-changelog/v3.5.1/distribution/index.js:1
module.exports =
^

ReferenceError: module is not defined
    at file:///home/runner/work/_actions/fregante/release-with-changelog/v3.5.1/distribution/index.js:1:1
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Any ideas why this might be happening and what I can do to fix it? 

Thanks
