### ISSUE TITLE
Error on protected branch: could not read Username for 'https://github.com/'

### ISSUE THREAD

**Issue by oc-stephen-bennett** [fregante/release-with-changelog#57]
Hi, 

Im using branch protection on master, but allowing bypass to a user with a PAT set to `${{ secrets.BYPASS }}` 

The below pipeline fails on the release step with this error. If there a work around? I believe its the `checkout@2` setting `persist-credentials: false` thats causing the error, but without it i cant get the `Automated Version Bump` step.

```
Run fregante/release-with-changelog@v3
Error: Command failed: git fetch origin +refs/tags/*:refs/tags/*
fatal: could not read Username for 'https://github.com/': No such device or address
```

Pipeline.yml

```
name: Push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
          fetch-depth: 50

      - name: Automated Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.BYPASS }}
        with:
          skip-tag: 'false'

      - name: Tag Changelog
        uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
