### ISSUE TITLE
The options don't work

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#6]
https://github.com/sindresorhus/refined-github/blob/18387e73251a024b26bb7d58f77d33bcae15b4cd/.github/workflows/deployment.yml#L27

```yml
      - uses: notlmn/release-with-changelog@v2
        with:
          include-range: false
          token: ${{ secrets.GITHUB_TOKEN }}
```

Generated:

```md
- [`18387e73`](https://github.com/sindresorhus/refined-github/commits/18387e73251a024b26bb7d58f77d33bcae15b4cd) Add `stop-pjax-loading-with-esc` feature (#3465)
- [`d8c1c195`](https://github.com/sindresorhus/refined-github/commits/d8c1c195cfdff5031fda6dc688ba36828e9d7d49) Remove `deinit` in `remove-label-faster` (#3538)
- [`2dc5f263`](https://github.com/sindresorhus/refined-github/commits/2dc5f263b97730b82ceee8cb64edc5da76fe5893) Purge expired cache items
- [`760abcfc`](https://github.com/sindresorhus/refined-github/commits/760abcfc4b2db013340241f87175a7b91ac11403) Correctly dim `bot` label in `dim-bots` (#3532)
- [`c254e559`](https://github.com/sindresorhus/refined-github/commits/c254e5596b852fa4b73177481bebc182f321b5d0) Ensure `batch-open-conversations` always adds every checkbox

[`20.9.4.1817..20.9.10`](https://github.com/sindresorhus/refined-github/compare/20.9.4.1817..20.9.10)
```

`include-range` is set to `false`, but the link is still included

**Comment by fregante** [comment]
https://github.com/fregante/github-url-detection/blob/9ed883648aeb95082f3fbea39364786708aba810/.github/workflows/publish.yml#L29-L31

```yml
      - uses: notlmn/release-with-changelog@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

Generated:

```yml
- [`12c7c075`](https://github.com/fregante/github-url-detection/commit/12c7c075edb4433248f4125fdcdb51233b97766e) Add `isNewRepo` (#33)

[`v2.0.6..v2.1.0`](https://github.com/fregante/github-url-detection/compare/v2.0.6..v2.1.0)
```

The default value for `include-hash` should be `false`, but it's still included.
