### ISSUE TITLE
Let the user specify a per-commit template

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#9]
Instead of using `include-hash`, this could allow a per-commit template so the user can customize it freely

```yml
with:
  template: '- {hash} {title}' # Default
```

```yml
with:
  template: '- {title} {hash}'
```
```yml
with:
  template: '{title} [🔗]({url})'
```

**Comment by fregante** [comment]
This should be relatively easy to implement:

```js
const line = template
  .replace('{hash}', commit.slice(0, 8))
  .replace('{title}', commit.slice(40))
  .replace('{url}', GITHUB_SERVER_URL + '/'+ GITHUB_REPOSITORY + '/commit/' + commit.slice(0, 40));
releaseBody.push(line);
```

**Comment by notlmn** [comment]
I suppose we can get `GITHUB_SERVER_URL + '/'+ GITHUB_REPOSITORY` with `git remote get-url origin`, unless SSH is being used in remotes.

**Comment by fregante** [comment]
> `GITHUB_SERVER_URL + '/'+ GITHUB_REPOSITORY`

Those are ENVs, immediately available, no need to execute `git`

https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

**Comment by fregante** [comment]
Heck, most options could be replaced by the template:

```yml
with:
  header: '### Changelog'
  footer: '❤️'
  include-range: true
```

```yml
with:
  template: |
    ### Changelog

    {commits}

    {range}

    ❤️
```

The advantage being that it provides real customization instead of just what we allow. Example currently impossible:

```yml
with:
  commit-template: '{title} ← {hash}'
  template: |
    {commits}

    Full diff: {range}
```
